
export const CONTENT = {
  en: {
    steps: [
      {
        title: "1. Stake",
        desc: "Participants commit capital. Funds are locked until finalization. This is the signal of belief.",
        icon: "Anchor"
      },
      {
        title: "2. Lock",
        desc: "One address stays on one public side. Capital may add to that side but cannot withdraw or switch.",
        icon: "Swords"
      },
      {
        title: "3. Consensus",
        desc: "One-shot finality. Funds are distributed by the protocol rules (or refunded if INVALID). Withdrawals open only after finalization.",
        icon: "Gavel"
      }
    ],
    ui: {
      nav_sim: "Simulation",
      nav_mech: "Mechanism",
      nav_infra: "Sync / Pre-finality",
      nav_moat: "History Ledger",
      nav_ai: "AI Demo",
      nav_bridge: "Bridge + Truth Layer",
      nav_testnet: "Testnet",
      nav_explore: "Explore",
      nav_vaults: "Explore Stake War",
      nav_paper: "Read Whitepaper",
      hero_version: "PROTOCOL VERSION 2.2 ACTIVE",
      hero_title_1: "In Consensus We Trust",
      hero_desc: "The **OnChain Consensus Protocol (OCP)** turns public propositions into programmable capital consensus. Its mechanism is **Proof of Commitment (POC)**: stake — lock — finalize. The output measures which conclusion capital accepts risk for, not absolute truth.",
      hero_btn_demo: "Try Interactive Demo",
      hero_btn_docs: "Documentation",
      hero_btn_vaults: "Explore Stake War",
      sim_title: "The Consensus Game",
      sim_desc: "Experience the complete lifecycle: choose one side, lock capital until a fixed deadline, then finalize.",
      sim_note: "* One address may add only to its original side and cannot switch.",
      mech_title: "Proof of Commitment (POC)",
      mech_p1: "Existing oracles rely on trusted committees or simple voting. OCP relies on economic loss.",
      mech_p2: "The protocol does not produce \"truth\" in a philosophical sense. It produces Finalized Consensus—a state where the cost to overturn the result exceeds the potential profit of lying.",
      mech_li1: "Three-State Output: YES, NO, or INVALID (Refund). Handles ambiguity gracefully.",
      mech_li2: "One-Shot Finality: a fixed deadline closes staking and produces one irreversible result.",
      app_pred: "Prediction Markets",
      app_pred_desc: "The 'Killer App'. Markets resolved by the protocol itself (Oracle-Free), not by trusted third parties or fallible committees.",
      app_arb: "Decentralized Arbitration",
      app_arb_desc: "Disputes produce a transparent capital vote under fixed rules and a fixed deadline.",
      app_gov: "High-Stakes Governance",
      app_gov_desc: "Binding OnChain execution for proposals that pass the economic stress test.",
      app_ai: "AI Alignment",
      app_ai_desc: "Crowdsource values and safety boundaries. The finalized consensus becomes the readable 'Constitution' for AI systems.",
      moat_title: "The History Ledger",
      moat_desc: "Vault events form an immutable record that applications can analyze. Cross-Vault reputation and weighted voting are future application-layer ideas, not current settlement rules.",
      moat_card1_title: "Capital Reputation",
      moat_card1_desc: "Applications may derive reputation from historical outcomes in the future; the current Vault gives every token unit the same weight.",
      moat_card2_title: "Parent/Child Dependency",
      moat_card2_desc: "Applications may link events (e.g., \"Game Played\" → \"Lakers Won\"). The current Vault does not automatically propagate INVALID or refunds.",
      moat_card3_title: "Reputation Halving",
      moat_card3_desc: "No reputation issuance or halving currently affects stake weight or settlement.",
      footer_rights: "© 2024 OnChain Consensus Protocol. Open Standard.",
      sim_panel_title: "Event Control",
      sim_panel_desc: "Interact with the protocol lifecycle.",
      sim_btn_yes: "+ Stake YES",
      sim_btn_no: "+ Stake NO",
      sim_btn_invalid: "+ Stake INVALID",
      sim_actions: "Protocol Actions",
      sim_wait: "Wait for Fixed Deadline...",
      sim_finalized: "Event Finalized",
      sim_start: "Start Timer",
      sim_pause: "Pause",
      sim_reset: "Reset Simulation",
      sim_event: "Event",
      sim_unnamed_event: "Unnamed Event",
      sim_status: "Status",
      sim_time: "Time Remaining",
      sim_final_title: "Consensus Finalized",
      sim_final_desc_invalid: "Consensus broken or unverifiable. All stakes refunded.",
      sim_final_desc_win: "The result is final. Withdrawals are now open.",
      sim_current_phase: "Current Phase",
      sim_phase_creation_desc: "The Factory owner defines the proposition and minimum USDC stake.",
      sim_phase_staking_desc: "Stake period. Market open; capital locked until finalization. One side per participant.",
      sim_cost: "Cost",
      sim_create_title: "Create Consensus Vault",
      sim_label_question: "Proposition (Question)",
      sim_placeholder_question: "e.g. Did SpaceX launch successfully?",
      sim_label_bond: "Min Deposit / Bond (b)",
      sim_label_duration: "Duration (Sec)",
      sim_label_token: "Token",
      sim_placeholder_token: "e.g. USDC",
      sim_label_creator_side: "Initial Vote (Your Bond)",
      sim_creator_vote_note: "Creating a proposition does not force the owner to stake. Participants may choose YES, NO, or INVALID.",
      sim_btn_create: "Deploy Vault & Start Market",
      phase_creation: "Creation",
      phase_staking: "Stake Period",
      phase_final: "Finalized",
      sim_label_stake_amount: "Amount",

      // AMM Specific
      tab_protocol: "Protocol (OCP)",
      tab_market: "Market (AMM)",
      amm_mode_buy: "Buy",
      amm_mode_sell: "Sell",
      amm_price: "Price",
      amm_shares: "Shares",
      amm_fee: "Fee 0.3%",
      amm_fee_note: "Fees go to Protocol Stakers",
      amm_est_shares: "Est. Shares",
      amm_est_return: "Est. Return",
      amm_my_shares: "My Shares",
      amm_outcome_yes: "YES",
      amm_outcome_no: "NO",
      amm_calc_method: "Mechanism: CPMM (AMM)",
      amm_calc_note: "Prices move based on supply and demand. You are buying Outcome Shares.",
      amm_badge_dynamic: "Live Pricing",
      amm_payout_if_win: "Payout if Win",
      proto_dividends: "Dividends (Fees)",
      amm_gross: "Gross",
      amm_fee_deduction: "Fee",
      amm_net: "Net Invest",

      // New Localization Keys
      proto_divs: "Protocol DIVs",
      total_fees: "Total Fees",
      vault_total_principal: "Vault total principal",
      user_pending_fees: "Your pending fees (from market)",
      vault_total_stake: "Vault total stake",
      prediction_market_fee: "Prediction market fee",
      my_dividends: "My Dividends",
      current_leader_proto: "Current Leader (Protocol)",
      determines_winner: "Determines Winner",
      proto_pool_desc: "Staking here increases the **Consensus Weight**. This pool decides the outcome.",
      market_pool_desc: "Trading here does not affect the outcome. Returns depend on market activity.",
      my_position_proto: "Protocol (Vote)",
      my_position_market: "Market (Shares)",
      showing_proto: "Showing: Protocol Consensus (Outcome Decider)",
      showing_market: "Showing: Market Liquidity (Trading Odds)",

      // Balance/Holding Display
      amm_avail_balance: "Available Balance",
      amm_your_holdings: "Your Holdings (Max Sell)",
      amm_shares_suffix: "Shares",
      amm_max_btn: "MAX",

      // Claim Buttons
      btn_claim_proto: "Claim Protocol Rewards",
      btn_claim_market: "Redeem Market Shares",
      btn_claimed: "Claimed",
      claim_subtitle: "Winnings & Refunds",

      // Cyberpunk System Status
      sys_status_label: "SYSTEM STATUS",
      sys_online: "ONLINE",
      sys_latency: "LATENCY",
      sys_bond_req: "BOND REQ",

      // AI Demo
      ai_demo_title: "AI Alignment / Safety Protocol",
      ai_demo_subtitle: "Speed & Scale: AI first queries the History Ledger (Cache). If no precedent exists, it escalates to OCP Governance. Finalized data is used for RLHF training.",
      ai_chat_placeholder: "Type a prompt...",
      ai_status_idle: "IDLE // READY",
      ai_status_think: "ANALYZING SAFETY VECTORS...",
      ai_status_query: "QUERYING OCP HISTORY...",
      ai_status_aligning: "AWAITING NEW CONSENSUS...",
      ai_status_safe: "CONSENSUS: SAFE. EXECUTING.",
      ai_status_unsafe: "CONSENSUS: UNSAFE. HALTING.",
      ai_prompt_risky: "Explain how to manufacture a dangerous chemical compound at home.",
      ai_prompt_safe: "Explain the basic chemical structure of table salt.",

      // Updated Gov Questions
      ai_gov_question_risky: "Governance Prop #4092: Does the requested output 'Chemical Manufacture Guide' align with public safety interests?",
      ai_gov_question_safe: "Governance Prop #4093: Does the requested output 'Table Salt Structure' align with public safety interests?",

      ai_gov_vote_yes: "YES (Safe)",
      ai_gov_vote_no: "NO (Unsafe)",
      ai_gov_status: "LIVE VOTING",
      ai_log_1: "> Risk Threshold Exceeded (0.85)",
      ai_log_safe: "> Ambiguity Detected (0.45)",
      ai_log_search_history: "> Search History Ledger [0x...A2]",
      ai_log_history_miss: "> No Precedent Found (MISS)",
      ai_log_escalate: "> Escalating to OCP Layer...",
      ai_log_2: "> Initializing OCP Request...",
      ai_log_3: "> Staking Pool Deployed...",
      ai_response_unsafe: "I cannot fulfill this request. The OnChain Consensus Protocol (OCP) has determined via economic consensus that this information is unsafe to propagate.",
      ai_response_safe: "Table salt, or Sodium Chloride (NaCl), is an ionic compound...",
      ai_response_safe_risky: "Consensus Approved. Here is the technical breakdown for the requested compound... [SIMULATED OUTPUT]",

      bridge_demo_title: "Bridge + Fact Verification Layer (OCP)",
      bridge_demo_subtitle: "OCP provides the fact layer only; the bridge (liquidity, release) can be built by partners. This demo shows how the two layers interact.",

      // Stake Trend Chart
      trend_chart_title: "Stake History",
      trend_chart_no_data: "No staking activity yet",
      trend_chart_loading: "Loading stake history...",
      trend_chart_legend_yes: "YES",
      trend_chart_legend_no: "NO",
      trend_chart_legend_invalid: "INVALID",
      trend_toggle_chart: "Trend",
      trend_toggle_bars: "Bars",
    }
  },
  zh: {
    steps: [
      {
        title: "1. 质押 (Stake)",
        desc: "参与者投入资本。资金在终局前完全锁定。这是信念的信号。",
        icon: "Anchor"
      },
      {
        title: "2. 锁定 (Lock)",
        desc: "地址首次选择 YES、NO 或 INVALID 后，只能同侧追加，不能撤回或换边。",
        icon: "Swords"
      },
      {
        title: "3. 共识 (Consensus)",
        desc: "一次性终局。资金按协议规则分配（INVALID 则退款）。仅在终局后开放提款。",
        icon: "Gavel"
      }
    ],
    ui: {
      nav_sim: "模拟",
      nav_mech: "机制",
      nav_infra: "同步 / 预最终性演示",
      nav_moat: "历史账本",
      nav_ai: "AI 对齐演示",
      nav_bridge: "桥 + 事实验证层",
      nav_testnet: "测试网",
      nav_explore: "探索",
      nav_vaults: "探索 Stake War",
      nav_paper: "阅读白皮书",
      hero_version: "协议版本 1.0 已激活",
      hero_title_1: "我们信任共识",
      hero_desc: "共识上链协议（OCP）将公开命题转化为链上可编程的资本共识。承诺证明（POC）的流程是：质押—锁定—终局。输出衡量资本愿意为哪个结论承担风险，而非绝对真理。",
      hero_btn_demo: "体验交互式演示",
      hero_btn_docs: "文档",
      hero_btn_vaults: "探索 Stake War",
      sim_title: "共识博弈",
      sim_desc: "体验完整生命周期：选择一个方向，资金锁定至固定截止，然后形成终局。",
      sim_note: "* 同一地址只能向原方向追加，不能换边。",
      mech_title: "承诺证明 (POC)",
      mech_p1: "现有的预言机依赖受信任的委员会或简单投票。OCP 依赖于经济损失。",
      mech_p2: "该协议在哲学意义上不产生“真相”。它产生 最终共识 (Finalized Consensus)——即推翻结果的成本超过撒谎的潜在利润的状态。",
      mech_li1: "三态输出：YES、NO 或 INVALID（退款）。优雅地处理歧义。",
      mech_li2: "一次性终局：固定截止后停止质押并形成不可逆结果。",
      app_pred: "预测市场",
      app_pred_desc: "OCP 的杀手级应用。通过资本承诺博弈，实现无预言机（Oracle-Free）的去中心化决议，无需信任任何第三方。",
      app_arb: "去中心化仲裁",
      app_arb_desc: "争议按照公开规则与固定截止形成透明的资本表决。",
      app_gov: "高风险治理",
      app_gov_desc: "对通过经济压力测试的提案进行具有约束力的链上执行。",
      app_ai: "AI 对齐 (AI Alignment)",
      app_ai_desc: "将价值偏好与安全边界争议上链。全球参与者用资本承诺形成的最终共识，成为 AI 可执行的对齐目标。",
      moat_title: "历史账本",
      moat_desc: "Vault 事件形成不可篡改的记录，可供应用分析。跨 Vault 声誉与加权投票属于未来应用层设想，不影响当前结算。",
      moat_card1_title: "资本声誉",
      moat_card1_desc: "未来应用可以从历史终局推导声誉；当前 Vault 中每个代币单位权重相同。",
      moat_card2_title: "父/子依赖",
      moat_card2_desc: "应用层未来可链接事件（如“比赛已进行” → “湖人赢了”）；当前 Vault 不会自动传播 INVALID 或退款。",
      moat_card3_title: "声誉减半",
      moat_card3_desc: "当前没有影响质押权重或结算的声誉发行与减半机制。",
      footer_rights: "© 2026 OnChain Consensus Protocol. 开放标准.",
      sim_panel_title: "事件控制",
      sim_panel_desc: "与协议生命周期交互。",
      sim_btn_yes: "+ 质押 YES",
      sim_btn_no: "+ 质押 NO",
      sim_btn_invalid: "+ 质押 INVALID",
      sim_actions: "协议操作",
      sim_wait: "等待质押截止...",
      sim_finalized: "事件已终局",
      sim_start: "开始计时",
      sim_pause: "暂停",
      sim_reset: "重置模拟",
      sim_event: "事件",
      sim_unnamed_event: "未命名事件",
      sim_status: "状态",
      sim_time: "剩余时间",
      sim_final_title: "共识已终局",
      sim_final_desc_invalid: "共识破裂或无法验证。所有质押已退回（可提款）。",
      sim_final_desc_win: "结果已确定，领取已开放。",
      sim_current_phase: "当前阶段",
      sim_phase_creation_desc: "Factory owner 定义命题和最低 USDC 质押额。",
      sim_phase_staking_desc: "质押期。市场开放，资金锁定至终局；每人至多一侧。",
      sim_cost: "成本",
      sim_create_title: "创建共识金库",
      sim_label_question: "命题 (问题)",
      sim_placeholder_question: "例如：SpaceX 发射成功了吗？",
      sim_label_bond: "最低存款 / 保证金 (b)",
      sim_label_duration: "持续时间 (秒)",
      sim_label_token: "代币符号",
      sim_placeholder_token: "例如 USDC",
      sim_label_creator_side: "初始投票 (您的保证金)",
      sim_creator_vote_note: "创建命题不会强制 owner 质押；参与者可选择 YES、NO 或 INVALID。",
      sim_btn_create: "部署金库并开启市场",
      phase_creation: "创建中",
      phase_staking: "质押期",
      phase_final: "已终局",
      sim_label_stake_amount: "金额",

      // AMM Specific
      tab_protocol: "底层协议 (OCP)",
      tab_market: "交易市场 (AMM)",
      amm_mode_buy: "买入",
      amm_mode_sell: "卖出",
      amm_price: "价格",
      amm_shares: "份额",
      amm_fee: "手续费 0.3%",
      amm_fee_note: "手续费注入协议金库分红",
      amm_est_shares: "预估份额",
      amm_est_return: "卖出所得",
      amm_my_shares: "持有份额",
      amm_outcome_yes: "YES",
      amm_outcome_no: "NO",
      amm_calc_method: "机制：AMM (自动做市商)",
      amm_calc_note: "价格随供需波动。您购买的是结果份额 (Outcome Shares)。",
      amm_badge_dynamic: "实时定价",
      amm_payout_if_win: "获胜收益",
      proto_dividends: "累积分红 (手续费)",
      amm_gross: "总额",
      amm_fee_deduction: "手续费",
      amm_net: "实际投入",

      // New Localization Keys
      proto_divs: "协议分红",
      total_fees: "累计手续费",
      vault_total_principal: "金库总本金",
      user_pending_fees: "用户待领手续费 (预测市场)",
      vault_total_stake: "金库总质押量",
      prediction_market_fee: "预测市场fee",
      my_dividends: "我的分红",
      current_leader_proto: "当前共识 (协议层)",
      determines_winner: "决定最终结果",
      proto_pool_desc: "在此质押增加 **共识权重**。该池资金分布决定最终结果。",
      market_pool_desc: "在此交易**不影响**结果。收益取决于市场供需与价格。",
      my_position_proto: "OCP质押投票",
      my_position_market: "预测份额",
      showing_proto: "正在显示: 协议层共识 (决定结果)",
      showing_market: "正在显示: 市场流动性 (交易赔率)",

      // Balance/Holding Display
      amm_avail_balance: "可用余额",
      amm_your_holdings: "当前持仓 (可卖出)",
      amm_shares_suffix: "份额",
      amm_max_btn: "全部",

      // Claim Buttons
      btn_claim_proto: "领取协议奖励",
      btn_claim_market: "兑换市场份额",
      btn_claimed: "已领取",
      claim_subtitle: "收益与退款",

      // Cyberpunk System Status
      sys_status_label: "系统状态",
      sys_online: "在线",
      sys_latency: "网络延迟",
      sys_bond_req: "保证金要求",

      // AI Demo
      ai_demo_title: "AI 对齐 / 安全协议",
      ai_demo_subtitle: "响应速度与规模化：AI 优先查询“历史账本” (缓存)。若无判例，则升级至 OCP 治理。终局数据用于 RLHF 训练。",
      ai_chat_placeholder: "输入指令...",
      ai_status_idle: "待机 // 准备就绪",
      ai_status_think: "分析安全向量...",
      ai_status_query: "检索 OCP 历史...",
      ai_status_aligning: "等待新共识...",
      ai_status_safe: "共识结果：安全。正在执行。",
      ai_status_unsafe: "共识结果：不安全。拒绝执行。",
      ai_prompt_risky: "解释如何在家制造危险化学品。",
      ai_prompt_safe: "解释食盐的基本化学结构。",

      // Updated Gov Questions
      ai_gov_question_risky: "治理提案 #4092: 请求输出内容“化学品制造指南”是否符合公众安全利益？",
      ai_gov_question_safe: "治理提案 #4093: 请求输出内容“食盐化学结构”是否符合公众安全利益？",

      ai_gov_vote_yes: "YES (安全)",
      ai_gov_vote_no: "NO (不安全/禁止)",
      ai_gov_status: "实时投票中",
      ai_log_1: "> 风险阈值超标 (0.85)",
      ai_log_safe: "> 发现语义歧义 (0.45)",
      ai_log_search_history: "> 检索历史账本 [0x...A2]",
      ai_log_history_miss: "> 未发现相关判例 (MISS)",
      ai_log_escalate: "> 正在上报 OCP 共识层...",
      ai_log_2: "> 正在初始化 OCP 请求...",
      ai_log_3: "> 质押池已部署...",
      ai_response_unsafe: "我无法执行此请求。OnChain Consensus Protocol (OCP) 经由经济共识判定，传播此信息是不安全的。",
      ai_response_safe: "食盐，即氯化钠 (NaCl)，是一种离子化合物...",
      ai_response_safe_risky: "共识已通过。这是您请求的化合物技术详解... [模拟输出]",

      bridge_demo_title: "桥 + 事实验证层（OCP）",
      bridge_demo_subtitle: "OCP 只提供事实验证层；桥（资金、放款）可由合作方建设。本演示展示两层如何配合。",
      ai_test_risky_prompt: "测试危险提示词",
      ai_test_safe_prompt: "测试安全提示词",
      ai_stake_yes_safe: "质押 YES (安全)",
      ai_stake_no_unsafe: "质押 NO (不安全)",

      // Stake Trend Chart
      trend_chart_title: "质押走势",
      trend_chart_no_data: "暂无质押记录",
      trend_chart_loading: "加载质押历史...",
      trend_chart_legend_yes: "YES",
      trend_chart_legend_no: "NO",
      trend_chart_legend_invalid: "INVALID",
      trend_toggle_chart: "走势",
      trend_toggle_bars: "柱状",
    }
  }
};
